stages:
  - build
  - test

image: gradle:7.6.0-jdk17

before_script:
  - echo "[ Starting CI ]"

build:
  stage: build
  script:
    - echo "[ Building ]"
    - ./gradlew clean build

test:
  stage: test
  script:
    - echo "[ Running Tests ]"
    - ./gradlew test

owasp-dependency-check:
  stage: test
  script:
    - echo "[ Running OWASP Dependency Check ]"
    - ./gradlew dependencyCheckAnalyze

after_script:
  - echo "[ Finished CI ]"