version: '3.9'

services:
  sonarqube:
    image: 'sonarqube:lts'
    ports:
      - '9000:9000'
    environment:
      - SONAR_FORCEAUTHENTICATION=false

  mongo-crypto-db:
    image: 'mongo:latest'
    container_name: 'mongo-crypto-db'
    ports:
      - '27017:27017'
    volumes:
      - crypto-db-volume:/data/db

  crypto-balance-tracker:
    image: 'crypto-balance-tracker:latest'
    container_name: 'crypto-balance-tracker'
    depends_on:
      - mongo-crypto-db
    environment:
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - COINGEKO_API_KEY=${COINGEKO_API_KEY}
    ports:
      - '8080:8080'

  crypto-balance-tracker-ui:
    image: 'crypto-balance-tracker-ui:latest'
    container_name: 'crypto-balance-tracker-ui'
    depends_on:
      - crypto-balance-tracker
    ports:
      - '5173:5173'

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana-oss:9.4.7
    user: "$UID:$GID"
    container_name: grafana-container
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost

volumes:
  crypto-db-volume: