scrape_configs:
  - job_name: 'Crypto Balance Tracker'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['crypto-balance-tracker:8080']
        labels:
          application: 'Crypto Balance Tracker Application'